org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Gradle chay bang JDK 20. AGP 8.x can JDK 17+, Gradle 8.3 ho tro toi da JDK 20.
org.gradle.java.home=/Users/shb_shds_05/Library/Java/JavaVirtualMachines/openjdk-20/Contents/Home
